package com.meituan.refund.entity;

import java.util.ArrayList;
import java.util.List;

public class RefundExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public RefundExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrder_idIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrder_idIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrder_idEqualTo(Integer value) {
			addCriterion("order_id =", value, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idNotEqualTo(Integer value) {
			addCriterion("order_id <>", value, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idGreaterThan(Integer value) {
			addCriterion("order_id >", value, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_id >=", value, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idLessThan(Integer value) {
			addCriterion("order_id <", value, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idLessThanOrEqualTo(Integer value) {
			addCriterion("order_id <=", value, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idIn(List<Integer> values) {
			addCriterion("order_id in", values, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idNotIn(List<Integer> values) {
			addCriterion("order_id not in", values, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idBetween(Integer value1, Integer value2) {
			addCriterion("order_id between", value1, value2, "order_id");
			return (Criteria) this;
		}

		public Criteria andOrder_idNotBetween(Integer value1, Integer value2) {
			addCriterion("order_id not between", value1, value2, "order_id");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeIsNull() {
			addCriterion("app_poi_code is null");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeIsNotNull() {
			addCriterion("app_poi_code is not null");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeEqualTo(String value) {
			addCriterion("app_poi_code =", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotEqualTo(String value) {
			addCriterion("app_poi_code <>", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeGreaterThan(String value) {
			addCriterion("app_poi_code >", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeGreaterThanOrEqualTo(String value) {
			addCriterion("app_poi_code >=", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeLessThan(String value) {
			addCriterion("app_poi_code <", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeLessThanOrEqualTo(String value) {
			addCriterion("app_poi_code <=", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeLike(String value) {
			addCriterion("app_poi_code like", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotLike(String value) {
			addCriterion("app_poi_code not like", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeIn(List<String> values) {
			addCriterion("app_poi_code in", values, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotIn(List<String> values) {
			addCriterion("app_poi_code not in", values, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeBetween(String value1, String value2) {
			addCriterion("app_poi_code between", value1, value2, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotBetween(String value1, String value2) {
			addCriterion("app_poi_code not between", value1, value2, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andNotify_typeIsNull() {
			addCriterion("notify_type is null");
			return (Criteria) this;
		}

		public Criteria andNotify_typeIsNotNull() {
			addCriterion("notify_type is not null");
			return (Criteria) this;
		}

		public Criteria andNotify_typeEqualTo(String value) {
			addCriterion("notify_type =", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeNotEqualTo(String value) {
			addCriterion("notify_type <>", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeGreaterThan(String value) {
			addCriterion("notify_type >", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeGreaterThanOrEqualTo(String value) {
			addCriterion("notify_type >=", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeLessThan(String value) {
			addCriterion("notify_type <", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeLessThanOrEqualTo(String value) {
			addCriterion("notify_type <=", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeLike(String value) {
			addCriterion("notify_type like", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeNotLike(String value) {
			addCriterion("notify_type not like", value, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeIn(List<String> values) {
			addCriterion("notify_type in", values, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeNotIn(List<String> values) {
			addCriterion("notify_type not in", values, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeBetween(String value1, String value2) {
			addCriterion("notify_type between", value1, value2, "notify_type");
			return (Criteria) this;
		}

		public Criteria andNotify_typeNotBetween(String value1, String value2) {
			addCriterion("notify_type not between", value1, value2, "notify_type");
			return (Criteria) this;
		}

		public Criteria andReasonIsNull() {
			addCriterion("reason is null");
			return (Criteria) this;
		}

		public Criteria andReasonIsNotNull() {
			addCriterion("reason is not null");
			return (Criteria) this;
		}

		public Criteria andReasonEqualTo(String value) {
			addCriterion("reason =", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotEqualTo(String value) {
			addCriterion("reason <>", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThan(String value) {
			addCriterion("reason >", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThanOrEqualTo(String value) {
			addCriterion("reason >=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThan(String value) {
			addCriterion("reason <", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThanOrEqualTo(String value) {
			addCriterion("reason <=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLike(String value) {
			addCriterion("reason like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotLike(String value) {
			addCriterion("reason not like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonIn(List<String> values) {
			addCriterion("reason in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotIn(List<String> values) {
			addCriterion("reason not in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonBetween(String value1, String value2) {
			addCriterion("reason between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotBetween(String value1, String value2) {
			addCriterion("reason not between", value1, value2, "reason");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table refund
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table refund
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 20 11:12:20 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}