package com.meituan.refund.entity;

public class Refund {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund.order_id
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	private Integer order_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund.app_poi_code
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	private String app_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund.notify_type
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	private String notify_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refund.reason
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	private String reason;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund.order_id
	 * @return  the value of refund.order_id
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public Integer getOrder_id() {
		return order_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund.order_id
	 * @param order_id  the value for refund.order_id
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void setOrder_id(Integer order_id) {
		this.order_id = order_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund.app_poi_code
	 * @return  the value of refund.app_poi_code
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public String getApp_poi_code() {
		return app_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund.app_poi_code
	 * @param app_poi_code  the value for refund.app_poi_code
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void setApp_poi_code(String app_poi_code) {
		this.app_poi_code = app_poi_code == null ? null : app_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund.notify_type
	 * @return  the value of refund.notify_type
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public String getNotify_type() {
		return notify_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund.notify_type
	 * @param notify_type  the value for refund.notify_type
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void setNotify_type(String notify_type) {
		this.notify_type = notify_type == null ? null : notify_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refund.reason
	 * @return  the value of refund.reason
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refund.reason
	 * @param reason  the value for refund.reason
	 * @mbggenerated  Wed Dec 02 20:17:12 CST 2015
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}
}