package com.meituan.refund.entity;

public class Refund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.order_id
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.notify_type
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    private String notify_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.reason
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.order_id
     *
     * @return the value of refund.order_id
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.order_id
     *
     * @param order_id the value for refund.order_id
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.notify_type
     *
     * @return the value of refund.notify_type
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    public String getNotify_type() {
        return notify_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.notify_type
     *
     * @param notify_type the value for refund.notify_type
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    public void setNotify_type(String notify_type) {
        this.notify_type = notify_type == null ? null : notify_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.reason
     *
     * @return the value of refund.reason
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.reason
     *
     * @param reason the value for refund.reason
     *
     * @mbggenerated Sun Sep 20 11:12:20 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}