package com.meituan.app.entity;

import java.util.Date;

public class App {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.appid
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.secret
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	private String secret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.userid
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.price
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.descption
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	private String descption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.expiredate
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	private Date expiredate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.appid
	 * @return  the value of app.appid
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.appid
	 * @param appid  the value for app.appid
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.secret
	 * @return  the value of app.secret
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public String getSecret() {
		return secret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.secret
	 * @param secret  the value for app.secret
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public void setSecret(String secret) {
		this.secret = secret == null ? null : secret.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.userid
	 * @return  the value of app.userid
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.userid
	 * @param userid  the value for app.userid
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.price
	 * @return  the value of app.price
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.price
	 * @param price  the value for app.price
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.descption
	 * @return  the value of app.descption
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public String getDescption() {
		return descption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.descption
	 * @param descption  the value for app.descption
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public void setDescption(String descption) {
		this.descption = descption == null ? null : descption.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.expiredate
	 * @return  the value of app.expiredate
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public Date getExpiredate() {
		return expiredate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.expiredate
	 * @param expiredate  the value for app.expiredate
	 * @mbggenerated  Fri Dec 18 20:55:48 CST 2015
	 */
	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}
}