package com.meituan.app.entity;

import java.util.Date;

public class App {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.appid
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.secret
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	private String secret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.desc
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.expiredate
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	private Date expiredate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.appid
	 * @return  the value of app.appid
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.appid
	 * @param appid  the value for app.appid
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.secret
	 * @return  the value of app.secret
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public String getSecret() {
		return secret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.secret
	 * @param secret  the value for app.secret
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void setSecret(String secret) {
		this.secret = secret == null ? null : secret.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.desc
	 * @return  the value of app.desc
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.desc
	 * @param desc  the value for app.desc
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.expiredate
	 * @return  the value of app.expiredate
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public Date getExpiredate() {
		return expiredate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.expiredate
	 * @param expiredate  the value for app.expiredate
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}
}