package com.meituan.app.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class AppExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public AppExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAppidIsNull() {
			addCriterion("appid is null");
			return (Criteria) this;
		}

		public Criteria andAppidIsNotNull() {
			addCriterion("appid is not null");
			return (Criteria) this;
		}

		public Criteria andAppidEqualTo(String value) {
			addCriterion("appid =", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotEqualTo(String value) {
			addCriterion("appid <>", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThan(String value) {
			addCriterion("appid >", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThanOrEqualTo(String value) {
			addCriterion("appid >=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThan(String value) {
			addCriterion("appid <", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThanOrEqualTo(String value) {
			addCriterion("appid <=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLike(String value) {
			addCriterion("appid like", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotLike(String value) {
			addCriterion("appid not like", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidIn(List<String> values) {
			addCriterion("appid in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotIn(List<String> values) {
			addCriterion("appid not in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidBetween(String value1, String value2) {
			addCriterion("appid between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotBetween(String value1, String value2) {
			addCriterion("appid not between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andSecretIsNull() {
			addCriterion("secret is null");
			return (Criteria) this;
		}

		public Criteria andSecretIsNotNull() {
			addCriterion("secret is not null");
			return (Criteria) this;
		}

		public Criteria andSecretEqualTo(String value) {
			addCriterion("secret =", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotEqualTo(String value) {
			addCriterion("secret <>", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretGreaterThan(String value) {
			addCriterion("secret >", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretGreaterThanOrEqualTo(String value) {
			addCriterion("secret >=", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLessThan(String value) {
			addCriterion("secret <", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLessThanOrEqualTo(String value) {
			addCriterion("secret <=", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLike(String value) {
			addCriterion("secret like", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotLike(String value) {
			addCriterion("secret not like", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretIn(List<String> values) {
			addCriterion("secret in", values, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotIn(List<String> values) {
			addCriterion("secret not in", values, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretBetween(String value1, String value2) {
			addCriterion("secret between", value1, value2, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotBetween(String value1, String value2) {
			addCriterion("secret not between", value1, value2, "secret");
			return (Criteria) this;
		}

		public Criteria andDescIsNull() {
			addCriterion("`desc` is null");
			return (Criteria) this;
		}

		public Criteria andDescIsNotNull() {
			addCriterion("`desc` is not null");
			return (Criteria) this;
		}

		public Criteria andDescEqualTo(String value) {
			addCriterion("`desc` =", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotEqualTo(String value) {
			addCriterion("`desc` <>", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescGreaterThan(String value) {
			addCriterion("`desc` >", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescGreaterThanOrEqualTo(String value) {
			addCriterion("`desc` >=", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLessThan(String value) {
			addCriterion("`desc` <", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLessThanOrEqualTo(String value) {
			addCriterion("`desc` <=", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLike(String value) {
			addCriterion("`desc` like", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotLike(String value) {
			addCriterion("`desc` not like", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescIn(List<String> values) {
			addCriterion("`desc` in", values, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotIn(List<String> values) {
			addCriterion("`desc` not in", values, "desc");
			return (Criteria) this;
		}

		public Criteria andDescBetween(String value1, String value2) {
			addCriterion("`desc` between", value1, value2, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotBetween(String value1, String value2) {
			addCriterion("`desc` not between", value1, value2, "desc");
			return (Criteria) this;
		}

		public Criteria andExpiredateIsNull() {
			addCriterion("expiredate is null");
			return (Criteria) this;
		}

		public Criteria andExpiredateIsNotNull() {
			addCriterion("expiredate is not null");
			return (Criteria) this;
		}

		public Criteria andExpiredateEqualTo(Date value) {
			addCriterion("expiredate =", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateNotEqualTo(Date value) {
			addCriterion("expiredate <>", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateGreaterThan(Date value) {
			addCriterion("expiredate >", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateGreaterThanOrEqualTo(Date value) {
			addCriterion("expiredate >=", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateLessThan(Date value) {
			addCriterion("expiredate <", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateLessThanOrEqualTo(Date value) {
			addCriterion("expiredate <=", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateIn(List<Date> values) {
			addCriterion("expiredate in", values, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateNotIn(List<Date> values) {
			addCriterion("expiredate not in", values, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateBetween(Date value1, Date value2) {
			addCriterion("expiredate between", value1, value2, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateNotBetween(Date value1, Date value2) {
			addCriterion("expiredate not between", value1, value2, "expiredate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app
	 * @mbggenerated  Wed Sep 09 22:01:04 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 09 21:58:06 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}