package com.meituan.detail.mapper;

import com.meituan.detail.entity.MeituanOrderDetail;
import com.meituan.detail.entity.MeituanOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeituanOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int countByExample(MeituanOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int deleteByExample(MeituanOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int insert(MeituanOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int insertSelective(MeituanOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    List<MeituanOrderDetail> selectByExample(MeituanOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    MeituanOrderDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") MeituanOrderDetail record, @Param("example") MeituanOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int updateByExample(@Param("record") MeituanOrderDetail record, @Param("example") MeituanOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int updateByPrimaryKeySelective(MeituanOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_detail
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    int updateByPrimaryKey(MeituanOrderDetail record);
}