package com.meituan.extras.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MeituanOrderExtrasExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public MeituanOrderExtrasExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActDetailIdIsNull() {
            addCriterion("act_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andActDetailIdIsNotNull() {
            addCriterion("act_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andActDetailIdEqualTo(Integer value) {
            addCriterion("act_detail_id =", value, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdNotEqualTo(Integer value) {
            addCriterion("act_detail_id <>", value, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdGreaterThan(Integer value) {
            addCriterion("act_detail_id >", value, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("act_detail_id >=", value, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdLessThan(Integer value) {
            addCriterion("act_detail_id <", value, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("act_detail_id <=", value, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdIn(List<Integer> values) {
            addCriterion("act_detail_id in", values, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdNotIn(List<Integer> values) {
            addCriterion("act_detail_id not in", values, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("act_detail_id between", value1, value2, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andActDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("act_detail_id not between", value1, value2, "actDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andReduceFeeIsNull() {
            addCriterion("reduce_fee is null");
            return (Criteria) this;
        }

        public Criteria andReduceFeeIsNotNull() {
            addCriterion("reduce_fee is not null");
            return (Criteria) this;
        }

        public Criteria andReduceFeeEqualTo(BigDecimal value) {
            addCriterion("reduce_fee =", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeNotEqualTo(BigDecimal value) {
            addCriterion("reduce_fee <>", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeGreaterThan(BigDecimal value) {
            addCriterion("reduce_fee >", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reduce_fee >=", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeLessThan(BigDecimal value) {
            addCriterion("reduce_fee <", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reduce_fee <=", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeIn(List<BigDecimal> values) {
            addCriterion("reduce_fee in", values, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeNotIn(List<BigDecimal> values) {
            addCriterion("reduce_fee not in", values, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduce_fee between", value1, value2, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduce_fee not between", value1, value2, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeIsNull() {
            addCriterion("avg_send_time is null");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeIsNotNull() {
            addCriterion("avg_send_time is not null");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeEqualTo(Integer value) {
            addCriterion("avg_send_time =", value, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeNotEqualTo(Integer value) {
            addCriterion("avg_send_time <>", value, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeGreaterThan(Integer value) {
            addCriterion("avg_send_time >", value, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("avg_send_time >=", value, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeLessThan(Integer value) {
            addCriterion("avg_send_time <", value, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeLessThanOrEqualTo(Integer value) {
            addCriterion("avg_send_time <=", value, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeIn(List<Integer> values) {
            addCriterion("avg_send_time in", values, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeNotIn(List<Integer> values) {
            addCriterion("avg_send_time not in", values, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeBetween(Integer value1, Integer value2) {
            addCriterion("avg_send_time between", value1, value2, "avgSendTime");
            return (Criteria) this;
        }

        public Criteria andAvgSendTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("avg_send_time not between", value1, value2, "avgSendTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meituan_order_extras
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 08 17:25:28 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meituan_order_extras
     *
     * @mbggenerated Tue Sep 08 17:25:28 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}