package com.meituan.order.entity;

import java.math.BigDecimal;

public class MeituanOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.order_id
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer order_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.wm_order_id_view
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Long wm_order_id_view;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.app_poi_code
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String app_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.wm_poi_name
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String wm_poi_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.wm_poi_address
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String wm_poi_address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.wm_poi_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String wm_poi_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.recipient_address
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String recipient_address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.recipient_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String recipient_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.recipient_name
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String recipient_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.shipping_fee
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Float shipping_fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.total
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Float total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.original_price
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private BigDecimal original_price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.caution
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String caution;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.shipper_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String shipper_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.status
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.city_id
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer city_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.has_invoiced
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer has_invoiced;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.invoice_title
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String invoice_title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.ctime
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.utime
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String utime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.delivery_time
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String delivery_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.is_third_shipping
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer is_third_shipping;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.pay_type
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer pay_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.latitude
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.longitude
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.detail
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.extra
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private String extra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meituan_order.app_status
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	private Integer app_status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.order_id
	 * @return  the value of meituan_order.order_id
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getOrder_id() {
		return order_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.order_id
	 * @param order_id  the value for meituan_order.order_id
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setOrder_id(Integer order_id) {
		this.order_id = order_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.wm_order_id_view
	 * @return  the value of meituan_order.wm_order_id_view
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Long getWm_order_id_view() {
		return wm_order_id_view;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.wm_order_id_view
	 * @param wm_order_id_view  the value for meituan_order.wm_order_id_view
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setWm_order_id_view(Long wm_order_id_view) {
		this.wm_order_id_view = wm_order_id_view;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.app_poi_code
	 * @return  the value of meituan_order.app_poi_code
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getApp_poi_code() {
		return app_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.app_poi_code
	 * @param app_poi_code  the value for meituan_order.app_poi_code
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setApp_poi_code(String app_poi_code) {
		this.app_poi_code = app_poi_code == null ? null : app_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.wm_poi_name
	 * @return  the value of meituan_order.wm_poi_name
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getWm_poi_name() {
		return wm_poi_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.wm_poi_name
	 * @param wm_poi_name  the value for meituan_order.wm_poi_name
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setWm_poi_name(String wm_poi_name) {
		this.wm_poi_name = wm_poi_name == null ? null : wm_poi_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.wm_poi_address
	 * @return  the value of meituan_order.wm_poi_address
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getWm_poi_address() {
		return wm_poi_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.wm_poi_address
	 * @param wm_poi_address  the value for meituan_order.wm_poi_address
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setWm_poi_address(String wm_poi_address) {
		this.wm_poi_address = wm_poi_address == null ? null : wm_poi_address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.wm_poi_phone
	 * @return  the value of meituan_order.wm_poi_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getWm_poi_phone() {
		return wm_poi_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.wm_poi_phone
	 * @param wm_poi_phone  the value for meituan_order.wm_poi_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setWm_poi_phone(String wm_poi_phone) {
		this.wm_poi_phone = wm_poi_phone == null ? null : wm_poi_phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.recipient_address
	 * @return  the value of meituan_order.recipient_address
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getRecipient_address() {
		return recipient_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.recipient_address
	 * @param recipient_address  the value for meituan_order.recipient_address
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setRecipient_address(String recipient_address) {
		this.recipient_address = recipient_address == null ? null : recipient_address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.recipient_phone
	 * @return  the value of meituan_order.recipient_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getRecipient_phone() {
		return recipient_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.recipient_phone
	 * @param recipient_phone  the value for meituan_order.recipient_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setRecipient_phone(String recipient_phone) {
		this.recipient_phone = recipient_phone == null ? null : recipient_phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.recipient_name
	 * @return  the value of meituan_order.recipient_name
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getRecipient_name() {
		return recipient_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.recipient_name
	 * @param recipient_name  the value for meituan_order.recipient_name
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setRecipient_name(String recipient_name) {
		this.recipient_name = recipient_name == null ? null : recipient_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.shipping_fee
	 * @return  the value of meituan_order.shipping_fee
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Float getShipping_fee() {
		return shipping_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.shipping_fee
	 * @param shipping_fee  the value for meituan_order.shipping_fee
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setShipping_fee(Float shipping_fee) {
		this.shipping_fee = shipping_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.total
	 * @return  the value of meituan_order.total
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Float getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.total
	 * @param total  the value for meituan_order.total
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setTotal(Float total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.original_price
	 * @return  the value of meituan_order.original_price
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public BigDecimal getOriginal_price() {
		return original_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.original_price
	 * @param original_price  the value for meituan_order.original_price
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setOriginal_price(BigDecimal original_price) {
		this.original_price = original_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.caution
	 * @return  the value of meituan_order.caution
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getCaution() {
		return caution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.caution
	 * @param caution  the value for meituan_order.caution
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setCaution(String caution) {
		this.caution = caution == null ? null : caution.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.shipper_phone
	 * @return  the value of meituan_order.shipper_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getShipper_phone() {
		return shipper_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.shipper_phone
	 * @param shipper_phone  the value for meituan_order.shipper_phone
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setShipper_phone(String shipper_phone) {
		this.shipper_phone = shipper_phone == null ? null : shipper_phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.status
	 * @return  the value of meituan_order.status
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.status
	 * @param status  the value for meituan_order.status
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.city_id
	 * @return  the value of meituan_order.city_id
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getCity_id() {
		return city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.city_id
	 * @param city_id  the value for meituan_order.city_id
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.has_invoiced
	 * @return  the value of meituan_order.has_invoiced
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getHas_invoiced() {
		return has_invoiced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.has_invoiced
	 * @param has_invoiced  the value for meituan_order.has_invoiced
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setHas_invoiced(Integer has_invoiced) {
		this.has_invoiced = has_invoiced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.invoice_title
	 * @return  the value of meituan_order.invoice_title
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getInvoice_title() {
		return invoice_title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.invoice_title
	 * @param invoice_title  the value for meituan_order.invoice_title
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setInvoice_title(String invoice_title) {
		this.invoice_title = invoice_title == null ? null : invoice_title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.ctime
	 * @return  the value of meituan_order.ctime
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.ctime
	 * @param ctime  the value for meituan_order.ctime
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setCtime(String ctime) {
		this.ctime = ctime == null ? null : ctime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.utime
	 * @return  the value of meituan_order.utime
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getUtime() {
		return utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.utime
	 * @param utime  the value for meituan_order.utime
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setUtime(String utime) {
		this.utime = utime == null ? null : utime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.delivery_time
	 * @return  the value of meituan_order.delivery_time
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getDelivery_time() {
		return delivery_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.delivery_time
	 * @param delivery_time  the value for meituan_order.delivery_time
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setDelivery_time(String delivery_time) {
		this.delivery_time = delivery_time == null ? null : delivery_time.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.is_third_shipping
	 * @return  the value of meituan_order.is_third_shipping
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getIs_third_shipping() {
		return is_third_shipping;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.is_third_shipping
	 * @param is_third_shipping  the value for meituan_order.is_third_shipping
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setIs_third_shipping(Integer is_third_shipping) {
		this.is_third_shipping = is_third_shipping;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.pay_type
	 * @return  the value of meituan_order.pay_type
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getPay_type() {
		return pay_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.pay_type
	 * @param pay_type  the value for meituan_order.pay_type
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setPay_type(Integer pay_type) {
		this.pay_type = pay_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.latitude
	 * @return  the value of meituan_order.latitude
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.latitude
	 * @param latitude  the value for meituan_order.latitude
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.longitude
	 * @return  the value of meituan_order.longitude
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.longitude
	 * @param longitude  the value for meituan_order.longitude
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.detail
	 * @return  the value of meituan_order.detail
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.detail
	 * @param detail  the value for meituan_order.detail
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setDetail(String detail) {
		this.detail = detail == null ? null : detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.extra
	 * @return  the value of meituan_order.extra
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public String getExtra() {
		return extra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.extra
	 * @param extra  the value for meituan_order.extra
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setExtra(String extra) {
		this.extra = extra == null ? null : extra.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meituan_order.app_status
	 * @return  the value of meituan_order.app_status
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public Integer getApp_status() {
		return app_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meituan_order.app_status
	 * @param app_status  the value for meituan_order.app_status
	 * @mbggenerated  Sat Sep 12 22:16:36 CST 2015
	 */
	public void setApp_status(Integer app_status) {
		this.app_status = app_status;
	}
}