package com.meituan.order.entity;

import java.math.BigDecimal;

public class MeituanOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.order_id
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.wm_order_id_view
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Long wmOrderIdView;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.app_poi_code
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String appPoiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.wm_poi_name
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String wmPoiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.wm_poi_address
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String wmPoiAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.wm_poi_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String wmPoiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.recipient_address
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String recipientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.recipient_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String recipientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.recipient_name
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String recipientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.shipping_fee
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Float shippingFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.total
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.original_price
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private BigDecimal originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.caution
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String caution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.shipper_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String shipperPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.status
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.city_id
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.has_invoiced
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer hasInvoiced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.invoice_title
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.ctime
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.utime
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.delivery_time
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.is_third_shipping
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer isThirdShipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.pay_type
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.latitude
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.longitude
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.detail
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.extra
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order.app_status
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    private Integer appStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.order_id
     *
     * @return the value of meituan_order.order_id
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.order_id
     *
     * @param orderId the value for meituan_order.order_id
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.wm_order_id_view
     *
     * @return the value of meituan_order.wm_order_id_view
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Long getWmOrderIdView() {
        return wmOrderIdView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.wm_order_id_view
     *
     * @param wmOrderIdView the value for meituan_order.wm_order_id_view
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setWmOrderIdView(Long wmOrderIdView) {
        this.wmOrderIdView = wmOrderIdView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.app_poi_code
     *
     * @return the value of meituan_order.app_poi_code
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getAppPoiCode() {
        return appPoiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.app_poi_code
     *
     * @param appPoiCode the value for meituan_order.app_poi_code
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setAppPoiCode(String appPoiCode) {
        this.appPoiCode = appPoiCode == null ? null : appPoiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.wm_poi_name
     *
     * @return the value of meituan_order.wm_poi_name
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getWmPoiName() {
        return wmPoiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.wm_poi_name
     *
     * @param wmPoiName the value for meituan_order.wm_poi_name
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setWmPoiName(String wmPoiName) {
        this.wmPoiName = wmPoiName == null ? null : wmPoiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.wm_poi_address
     *
     * @return the value of meituan_order.wm_poi_address
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getWmPoiAddress() {
        return wmPoiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.wm_poi_address
     *
     * @param wmPoiAddress the value for meituan_order.wm_poi_address
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setWmPoiAddress(String wmPoiAddress) {
        this.wmPoiAddress = wmPoiAddress == null ? null : wmPoiAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.wm_poi_phone
     *
     * @return the value of meituan_order.wm_poi_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getWmPoiPhone() {
        return wmPoiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.wm_poi_phone
     *
     * @param wmPoiPhone the value for meituan_order.wm_poi_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setWmPoiPhone(String wmPoiPhone) {
        this.wmPoiPhone = wmPoiPhone == null ? null : wmPoiPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.recipient_address
     *
     * @return the value of meituan_order.recipient_address
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.recipient_address
     *
     * @param recipientAddress the value for meituan_order.recipient_address
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress == null ? null : recipientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.recipient_phone
     *
     * @return the value of meituan_order.recipient_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getRecipientPhone() {
        return recipientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.recipient_phone
     *
     * @param recipientPhone the value for meituan_order.recipient_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setRecipientPhone(String recipientPhone) {
        this.recipientPhone = recipientPhone == null ? null : recipientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.recipient_name
     *
     * @return the value of meituan_order.recipient_name
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.recipient_name
     *
     * @param recipientName the value for meituan_order.recipient_name
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName == null ? null : recipientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.shipping_fee
     *
     * @return the value of meituan_order.shipping_fee
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Float getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.shipping_fee
     *
     * @param shippingFee the value for meituan_order.shipping_fee
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setShippingFee(Float shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.total
     *
     * @return the value of meituan_order.total
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.total
     *
     * @param total the value for meituan_order.total
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.original_price
     *
     * @return the value of meituan_order.original_price
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.original_price
     *
     * @param originalPrice the value for meituan_order.original_price
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.caution
     *
     * @return the value of meituan_order.caution
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getCaution() {
        return caution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.caution
     *
     * @param caution the value for meituan_order.caution
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setCaution(String caution) {
        this.caution = caution == null ? null : caution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.shipper_phone
     *
     * @return the value of meituan_order.shipper_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getShipperPhone() {
        return shipperPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.shipper_phone
     *
     * @param shipperPhone the value for meituan_order.shipper_phone
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setShipperPhone(String shipperPhone) {
        this.shipperPhone = shipperPhone == null ? null : shipperPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.status
     *
     * @return the value of meituan_order.status
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.status
     *
     * @param status the value for meituan_order.status
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.city_id
     *
     * @return the value of meituan_order.city_id
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.city_id
     *
     * @param cityId the value for meituan_order.city_id
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.has_invoiced
     *
     * @return the value of meituan_order.has_invoiced
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getHasInvoiced() {
        return hasInvoiced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.has_invoiced
     *
     * @param hasInvoiced the value for meituan_order.has_invoiced
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setHasInvoiced(Integer hasInvoiced) {
        this.hasInvoiced = hasInvoiced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.invoice_title
     *
     * @return the value of meituan_order.invoice_title
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.invoice_title
     *
     * @param invoiceTitle the value for meituan_order.invoice_title
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.ctime
     *
     * @return the value of meituan_order.ctime
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.ctime
     *
     * @param ctime the value for meituan_order.ctime
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.utime
     *
     * @return the value of meituan_order.utime
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.utime
     *
     * @param utime the value for meituan_order.utime
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setUtime(String utime) {
        this.utime = utime == null ? null : utime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.delivery_time
     *
     * @return the value of meituan_order.delivery_time
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.delivery_time
     *
     * @param deliveryTime the value for meituan_order.delivery_time
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.is_third_shipping
     *
     * @return the value of meituan_order.is_third_shipping
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getIsThirdShipping() {
        return isThirdShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.is_third_shipping
     *
     * @param isThirdShipping the value for meituan_order.is_third_shipping
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setIsThirdShipping(Integer isThirdShipping) {
        this.isThirdShipping = isThirdShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.pay_type
     *
     * @return the value of meituan_order.pay_type
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.pay_type
     *
     * @param payType the value for meituan_order.pay_type
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.latitude
     *
     * @return the value of meituan_order.latitude
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.latitude
     *
     * @param latitude the value for meituan_order.latitude
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.longitude
     *
     * @return the value of meituan_order.longitude
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.longitude
     *
     * @param longitude the value for meituan_order.longitude
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.detail
     *
     * @return the value of meituan_order.detail
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.detail
     *
     * @param detail the value for meituan_order.detail
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.extra
     *
     * @return the value of meituan_order.extra
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.extra
     *
     * @param extra the value for meituan_order.extra
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order.app_status
     *
     * @return the value of meituan_order.app_status
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Integer getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order.app_status
     *
     * @param appStatus the value for meituan_order.app_status
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setAppStatus(Integer appStatus) {
        this.appStatus = appStatus;
    }
}