package com.meituan.order.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MeituanOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public MeituanOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewIsNull() {
            addCriterion("wm_order_id_view is null");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewIsNotNull() {
            addCriterion("wm_order_id_view is not null");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewEqualTo(Long value) {
            addCriterion("wm_order_id_view =", value, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewNotEqualTo(Long value) {
            addCriterion("wm_order_id_view <>", value, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewGreaterThan(Long value) {
            addCriterion("wm_order_id_view >", value, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewGreaterThanOrEqualTo(Long value) {
            addCriterion("wm_order_id_view >=", value, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewLessThan(Long value) {
            addCriterion("wm_order_id_view <", value, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewLessThanOrEqualTo(Long value) {
            addCriterion("wm_order_id_view <=", value, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewIn(List<Long> values) {
            addCriterion("wm_order_id_view in", values, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewNotIn(List<Long> values) {
            addCriterion("wm_order_id_view not in", values, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewBetween(Long value1, Long value2) {
            addCriterion("wm_order_id_view between", value1, value2, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andWmOrderIdViewNotBetween(Long value1, Long value2) {
            addCriterion("wm_order_id_view not between", value1, value2, "wmOrderIdView");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeIsNull() {
            addCriterion("app_poi_code is null");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeIsNotNull() {
            addCriterion("app_poi_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeEqualTo(String value) {
            addCriterion("app_poi_code =", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotEqualTo(String value) {
            addCriterion("app_poi_code <>", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeGreaterThan(String value) {
            addCriterion("app_poi_code >", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeGreaterThanOrEqualTo(String value) {
            addCriterion("app_poi_code >=", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeLessThan(String value) {
            addCriterion("app_poi_code <", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeLessThanOrEqualTo(String value) {
            addCriterion("app_poi_code <=", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeLike(String value) {
            addCriterion("app_poi_code like", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotLike(String value) {
            addCriterion("app_poi_code not like", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeIn(List<String> values) {
            addCriterion("app_poi_code in", values, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotIn(List<String> values) {
            addCriterion("app_poi_code not in", values, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeBetween(String value1, String value2) {
            addCriterion("app_poi_code between", value1, value2, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotBetween(String value1, String value2) {
            addCriterion("app_poi_code not between", value1, value2, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameIsNull() {
            addCriterion("wm_poi_name is null");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameIsNotNull() {
            addCriterion("wm_poi_name is not null");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameEqualTo(String value) {
            addCriterion("wm_poi_name =", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameNotEqualTo(String value) {
            addCriterion("wm_poi_name <>", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameGreaterThan(String value) {
            addCriterion("wm_poi_name >", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameGreaterThanOrEqualTo(String value) {
            addCriterion("wm_poi_name >=", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameLessThan(String value) {
            addCriterion("wm_poi_name <", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameLessThanOrEqualTo(String value) {
            addCriterion("wm_poi_name <=", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameLike(String value) {
            addCriterion("wm_poi_name like", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameNotLike(String value) {
            addCriterion("wm_poi_name not like", value, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameIn(List<String> values) {
            addCriterion("wm_poi_name in", values, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameNotIn(List<String> values) {
            addCriterion("wm_poi_name not in", values, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameBetween(String value1, String value2) {
            addCriterion("wm_poi_name between", value1, value2, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiNameNotBetween(String value1, String value2) {
            addCriterion("wm_poi_name not between", value1, value2, "wmPoiName");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressIsNull() {
            addCriterion("wm_poi_address is null");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressIsNotNull() {
            addCriterion("wm_poi_address is not null");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressEqualTo(String value) {
            addCriterion("wm_poi_address =", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressNotEqualTo(String value) {
            addCriterion("wm_poi_address <>", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressGreaterThan(String value) {
            addCriterion("wm_poi_address >", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressGreaterThanOrEqualTo(String value) {
            addCriterion("wm_poi_address >=", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressLessThan(String value) {
            addCriterion("wm_poi_address <", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressLessThanOrEqualTo(String value) {
            addCriterion("wm_poi_address <=", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressLike(String value) {
            addCriterion("wm_poi_address like", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressNotLike(String value) {
            addCriterion("wm_poi_address not like", value, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressIn(List<String> values) {
            addCriterion("wm_poi_address in", values, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressNotIn(List<String> values) {
            addCriterion("wm_poi_address not in", values, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressBetween(String value1, String value2) {
            addCriterion("wm_poi_address between", value1, value2, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiAddressNotBetween(String value1, String value2) {
            addCriterion("wm_poi_address not between", value1, value2, "wmPoiAddress");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneIsNull() {
            addCriterion("wm_poi_phone is null");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneIsNotNull() {
            addCriterion("wm_poi_phone is not null");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneEqualTo(String value) {
            addCriterion("wm_poi_phone =", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneNotEqualTo(String value) {
            addCriterion("wm_poi_phone <>", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneGreaterThan(String value) {
            addCriterion("wm_poi_phone >", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("wm_poi_phone >=", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneLessThan(String value) {
            addCriterion("wm_poi_phone <", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneLessThanOrEqualTo(String value) {
            addCriterion("wm_poi_phone <=", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneLike(String value) {
            addCriterion("wm_poi_phone like", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneNotLike(String value) {
            addCriterion("wm_poi_phone not like", value, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneIn(List<String> values) {
            addCriterion("wm_poi_phone in", values, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneNotIn(List<String> values) {
            addCriterion("wm_poi_phone not in", values, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneBetween(String value1, String value2) {
            addCriterion("wm_poi_phone between", value1, value2, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andWmPoiPhoneNotBetween(String value1, String value2) {
            addCriterion("wm_poi_phone not between", value1, value2, "wmPoiPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIsNull() {
            addCriterion("recipient_address is null");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIsNotNull() {
            addCriterion("recipient_address is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressEqualTo(String value) {
            addCriterion("recipient_address =", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotEqualTo(String value) {
            addCriterion("recipient_address <>", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressGreaterThan(String value) {
            addCriterion("recipient_address >", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_address >=", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLessThan(String value) {
            addCriterion("recipient_address <", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLessThanOrEqualTo(String value) {
            addCriterion("recipient_address <=", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLike(String value) {
            addCriterion("recipient_address like", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotLike(String value) {
            addCriterion("recipient_address not like", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIn(List<String> values) {
            addCriterion("recipient_address in", values, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotIn(List<String> values) {
            addCriterion("recipient_address not in", values, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressBetween(String value1, String value2) {
            addCriterion("recipient_address between", value1, value2, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotBetween(String value1, String value2) {
            addCriterion("recipient_address not between", value1, value2, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneIsNull() {
            addCriterion("recipient_phone is null");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneIsNotNull() {
            addCriterion("recipient_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneEqualTo(String value) {
            addCriterion("recipient_phone =", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotEqualTo(String value) {
            addCriterion("recipient_phone <>", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneGreaterThan(String value) {
            addCriterion("recipient_phone >", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_phone >=", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneLessThan(String value) {
            addCriterion("recipient_phone <", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneLessThanOrEqualTo(String value) {
            addCriterion("recipient_phone <=", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneLike(String value) {
            addCriterion("recipient_phone like", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotLike(String value) {
            addCriterion("recipient_phone not like", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneIn(List<String> values) {
            addCriterion("recipient_phone in", values, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotIn(List<String> values) {
            addCriterion("recipient_phone not in", values, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneBetween(String value1, String value2) {
            addCriterion("recipient_phone between", value1, value2, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotBetween(String value1, String value2) {
            addCriterion("recipient_phone not between", value1, value2, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIsNull() {
            addCriterion("recipient_name is null");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIsNotNull() {
            addCriterion("recipient_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientNameEqualTo(String value) {
            addCriterion("recipient_name =", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotEqualTo(String value) {
            addCriterion("recipient_name <>", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameGreaterThan(String value) {
            addCriterion("recipient_name >", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_name >=", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLessThan(String value) {
            addCriterion("recipient_name <", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLessThanOrEqualTo(String value) {
            addCriterion("recipient_name <=", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLike(String value) {
            addCriterion("recipient_name like", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotLike(String value) {
            addCriterion("recipient_name not like", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIn(List<String> values) {
            addCriterion("recipient_name in", values, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotIn(List<String> values) {
            addCriterion("recipient_name not in", values, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameBetween(String value1, String value2) {
            addCriterion("recipient_name between", value1, value2, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotBetween(String value1, String value2) {
            addCriterion("recipient_name not between", value1, value2, "recipientName");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIsNull() {
            addCriterion("shipping_fee is null");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIsNotNull() {
            addCriterion("shipping_fee is not null");
            return (Criteria) this;
        }

        public Criteria andShippingFeeEqualTo(Float value) {
            addCriterion("shipping_fee =", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotEqualTo(Float value) {
            addCriterion("shipping_fee <>", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeGreaterThan(Float value) {
            addCriterion("shipping_fee >", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeGreaterThanOrEqualTo(Float value) {
            addCriterion("shipping_fee >=", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeLessThan(Float value) {
            addCriterion("shipping_fee <", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeLessThanOrEqualTo(Float value) {
            addCriterion("shipping_fee <=", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIn(List<Float> values) {
            addCriterion("shipping_fee in", values, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotIn(List<Float> values) {
            addCriterion("shipping_fee not in", values, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeBetween(Float value1, Float value2) {
            addCriterion("shipping_fee between", value1, value2, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotBetween(Float value1, Float value2) {
            addCriterion("shipping_fee not between", value1, value2, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Float value) {
            addCriterion("total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Float value) {
            addCriterion("total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Float value) {
            addCriterion("total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Float value) {
            addCriterion("total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Float value) {
            addCriterion("total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Float value) {
            addCriterion("total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Float> values) {
            addCriterion("total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Float> values) {
            addCriterion("total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Float value1, Float value2) {
            addCriterion("total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Float value1, Float value2) {
            addCriterion("total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNull() {
            addCriterion("original_price is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNotNull() {
            addCriterion("original_price is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceEqualTo(BigDecimal value) {
            addCriterion("original_price =", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotEqualTo(BigDecimal value) {
            addCriterion("original_price <>", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThan(BigDecimal value) {
            addCriterion("original_price >", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("original_price >=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThan(BigDecimal value) {
            addCriterion("original_price <", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("original_price <=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIn(List<BigDecimal> values) {
            addCriterion("original_price in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotIn(List<BigDecimal> values) {
            addCriterion("original_price not in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("original_price between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("original_price not between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andCautionIsNull() {
            addCriterion("caution is null");
            return (Criteria) this;
        }

        public Criteria andCautionIsNotNull() {
            addCriterion("caution is not null");
            return (Criteria) this;
        }

        public Criteria andCautionEqualTo(String value) {
            addCriterion("caution =", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionNotEqualTo(String value) {
            addCriterion("caution <>", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionGreaterThan(String value) {
            addCriterion("caution >", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionGreaterThanOrEqualTo(String value) {
            addCriterion("caution >=", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionLessThan(String value) {
            addCriterion("caution <", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionLessThanOrEqualTo(String value) {
            addCriterion("caution <=", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionLike(String value) {
            addCriterion("caution like", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionNotLike(String value) {
            addCriterion("caution not like", value, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionIn(List<String> values) {
            addCriterion("caution in", values, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionNotIn(List<String> values) {
            addCriterion("caution not in", values, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionBetween(String value1, String value2) {
            addCriterion("caution between", value1, value2, "caution");
            return (Criteria) this;
        }

        public Criteria andCautionNotBetween(String value1, String value2) {
            addCriterion("caution not between", value1, value2, "caution");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneIsNull() {
            addCriterion("shipper_phone is null");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneIsNotNull() {
            addCriterion("shipper_phone is not null");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneEqualTo(String value) {
            addCriterion("shipper_phone =", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneNotEqualTo(String value) {
            addCriterion("shipper_phone <>", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneGreaterThan(String value) {
            addCriterion("shipper_phone >", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("shipper_phone >=", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneLessThan(String value) {
            addCriterion("shipper_phone <", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneLessThanOrEqualTo(String value) {
            addCriterion("shipper_phone <=", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneLike(String value) {
            addCriterion("shipper_phone like", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneNotLike(String value) {
            addCriterion("shipper_phone not like", value, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneIn(List<String> values) {
            addCriterion("shipper_phone in", values, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneNotIn(List<String> values) {
            addCriterion("shipper_phone not in", values, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneBetween(String value1, String value2) {
            addCriterion("shipper_phone between", value1, value2, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andShipperPhoneNotBetween(String value1, String value2) {
            addCriterion("shipper_phone not between", value1, value2, "shipperPhone");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Integer value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Integer value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Integer value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Integer value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Integer> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Integer> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Integer value1, Integer value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedIsNull() {
            addCriterion("has_invoiced is null");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedIsNotNull() {
            addCriterion("has_invoiced is not null");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedEqualTo(Integer value) {
            addCriterion("has_invoiced =", value, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedNotEqualTo(Integer value) {
            addCriterion("has_invoiced <>", value, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedGreaterThan(Integer value) {
            addCriterion("has_invoiced >", value, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedGreaterThanOrEqualTo(Integer value) {
            addCriterion("has_invoiced >=", value, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedLessThan(Integer value) {
            addCriterion("has_invoiced <", value, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedLessThanOrEqualTo(Integer value) {
            addCriterion("has_invoiced <=", value, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedIn(List<Integer> values) {
            addCriterion("has_invoiced in", values, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedNotIn(List<Integer> values) {
            addCriterion("has_invoiced not in", values, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedBetween(Integer value1, Integer value2) {
            addCriterion("has_invoiced between", value1, value2, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andHasInvoicedNotBetween(Integer value1, Integer value2) {
            addCriterion("has_invoiced not between", value1, value2, "hasInvoiced");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleIsNull() {
            addCriterion("invoice_title is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleIsNotNull() {
            addCriterion("invoice_title is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleEqualTo(String value) {
            addCriterion("invoice_title =", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleNotEqualTo(String value) {
            addCriterion("invoice_title <>", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleGreaterThan(String value) {
            addCriterion("invoice_title >", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleGreaterThanOrEqualTo(String value) {
            addCriterion("invoice_title >=", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleLessThan(String value) {
            addCriterion("invoice_title <", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleLessThanOrEqualTo(String value) {
            addCriterion("invoice_title <=", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleLike(String value) {
            addCriterion("invoice_title like", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleNotLike(String value) {
            addCriterion("invoice_title not like", value, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleIn(List<String> values) {
            addCriterion("invoice_title in", values, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleNotIn(List<String> values) {
            addCriterion("invoice_title not in", values, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleBetween(String value1, String value2) {
            addCriterion("invoice_title between", value1, value2, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andInvoiceTitleNotBetween(String value1, String value2) {
            addCriterion("invoice_title not between", value1, value2, "invoiceTitle");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(String value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(String value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(String value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(String value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(String value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLike(String value) {
            addCriterion("ctime like", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotLike(String value) {
            addCriterion("ctime not like", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<String> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<String> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(String value1, String value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(String value1, String value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(String value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(String value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(String value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(String value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(String value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(String value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLike(String value) {
            addCriterion("utime like", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotLike(String value) {
            addCriterion("utime not like", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<String> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<String> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(String value1, String value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(String value1, String value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNull() {
            addCriterion("delivery_time is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNotNull() {
            addCriterion("delivery_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeEqualTo(String value) {
            addCriterion("delivery_time =", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotEqualTo(String value) {
            addCriterion("delivery_time <>", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThan(String value) {
            addCriterion("delivery_time >", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_time >=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThan(String value) {
            addCriterion("delivery_time <", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThanOrEqualTo(String value) {
            addCriterion("delivery_time <=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLike(String value) {
            addCriterion("delivery_time like", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotLike(String value) {
            addCriterion("delivery_time not like", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIn(List<String> values) {
            addCriterion("delivery_time in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotIn(List<String> values) {
            addCriterion("delivery_time not in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeBetween(String value1, String value2) {
            addCriterion("delivery_time between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotBetween(String value1, String value2) {
            addCriterion("delivery_time not between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingIsNull() {
            addCriterion("is_third_shipping is null");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingIsNotNull() {
            addCriterion("is_third_shipping is not null");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingEqualTo(Integer value) {
            addCriterion("is_third_shipping =", value, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingNotEqualTo(Integer value) {
            addCriterion("is_third_shipping <>", value, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingGreaterThan(Integer value) {
            addCriterion("is_third_shipping >", value, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_third_shipping >=", value, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingLessThan(Integer value) {
            addCriterion("is_third_shipping <", value, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingLessThanOrEqualTo(Integer value) {
            addCriterion("is_third_shipping <=", value, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingIn(List<Integer> values) {
            addCriterion("is_third_shipping in", values, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingNotIn(List<Integer> values) {
            addCriterion("is_third_shipping not in", values, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingBetween(Integer value1, Integer value2) {
            addCriterion("is_third_shipping between", value1, value2, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andIsThirdShippingNotBetween(Integer value1, Integer value2) {
            addCriterion("is_third_shipping not between", value1, value2, "isThirdShipping");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(Integer value) {
            addCriterion("pay_type =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(Integer value) {
            addCriterion("pay_type <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(Integer value) {
            addCriterion("pay_type >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_type >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(Integer value) {
            addCriterion("pay_type <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_type <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<Integer> values) {
            addCriterion("pay_type in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<Integer> values) {
            addCriterion("pay_type not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("pay_type between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_type not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andExtraIsNull() {
            addCriterion("extra is null");
            return (Criteria) this;
        }

        public Criteria andExtraIsNotNull() {
            addCriterion("extra is not null");
            return (Criteria) this;
        }

        public Criteria andExtraEqualTo(String value) {
            addCriterion("extra =", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotEqualTo(String value) {
            addCriterion("extra <>", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThan(String value) {
            addCriterion("extra >", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThanOrEqualTo(String value) {
            addCriterion("extra >=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThan(String value) {
            addCriterion("extra <", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThanOrEqualTo(String value) {
            addCriterion("extra <=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLike(String value) {
            addCriterion("extra like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotLike(String value) {
            addCriterion("extra not like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraIn(List<String> values) {
            addCriterion("extra in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotIn(List<String> values) {
            addCriterion("extra not in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraBetween(String value1, String value2) {
            addCriterion("extra between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotBetween(String value1, String value2) {
            addCriterion("extra not between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andAppStatusIsNull() {
            addCriterion("app_status is null");
            return (Criteria) this;
        }

        public Criteria andAppStatusIsNotNull() {
            addCriterion("app_status is not null");
            return (Criteria) this;
        }

        public Criteria andAppStatusEqualTo(Integer value) {
            addCriterion("app_status =", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotEqualTo(Integer value) {
            addCriterion("app_status <>", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusGreaterThan(Integer value) {
            addCriterion("app_status >", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_status >=", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLessThan(Integer value) {
            addCriterion("app_status <", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLessThanOrEqualTo(Integer value) {
            addCriterion("app_status <=", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusIn(List<Integer> values) {
            addCriterion("app_status in", values, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotIn(List<Integer> values) {
            addCriterion("app_status not in", values, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusBetween(Integer value1, Integer value2) {
            addCriterion("app_status between", value1, value2, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("app_status not between", value1, value2, "appStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meituan_order
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 10 20:54:24 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meituan_order
     *
     * @mbggenerated Thu Sep 10 20:54:24 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}