package com.meituan.apppoi.mapper;

import com.meituan.apppoi.entity.AppPoi;
import com.meituan.apppoi.entity.AppPoiExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.meituan.apppoi.entity.AppPoiKey;

public interface AppPoiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int countByExample(AppPoiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int deleteByExample(AppPoiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int deleteByPrimaryKey(Integer poi_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int insert(AppPoi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int insertSelective(AppPoi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	List<AppPoi> selectByExample(AppPoiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	AppPoi selectByPrimaryKey(Integer poi_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int updateByExampleSelective(@Param("record") AppPoi record, @Param("example") AppPoiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int updateByExample(@Param("record") AppPoi record, @Param("example") AppPoiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int updateByPrimaryKeySelective(AppPoi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	int updateByPrimaryKey(AppPoi record);

	/**
	 * 分页查询
	 * @param beginNum
	 * @param endNum
	 * @param userId
	 * @return
	 */
	List<AppPoi> selectLimt(int beginNum,int endNum,  @Param("example") AppPoiExample example);
}