package com.meituan.detail.entity;

import java.math.BigDecimal;

public class MeituanOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.detail_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.order_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.app_food_code
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private Integer appFoodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.food_name
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private String foodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.sku_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private String skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.quantity
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.price
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.box_num
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private Integer boxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.box_price
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private BigDecimal boxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.unit
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meituan_order_detail.food_discount
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    private BigDecimal foodDiscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.detail_id
     *
     * @return the value of meituan_order_detail.detail_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.detail_id
     *
     * @param detailId the value for meituan_order_detail.detail_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.order_id
     *
     * @return the value of meituan_order_detail.order_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.order_id
     *
     * @param orderId the value for meituan_order_detail.order_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.app_food_code
     *
     * @return the value of meituan_order_detail.app_food_code
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public Integer getAppFoodCode() {
        return appFoodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.app_food_code
     *
     * @param appFoodCode the value for meituan_order_detail.app_food_code
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setAppFoodCode(Integer appFoodCode) {
        this.appFoodCode = appFoodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.food_name
     *
     * @return the value of meituan_order_detail.food_name
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.food_name
     *
     * @param foodName the value for meituan_order_detail.food_name
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.sku_id
     *
     * @return the value of meituan_order_detail.sku_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.sku_id
     *
     * @param skuId the value for meituan_order_detail.sku_id
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.quantity
     *
     * @return the value of meituan_order_detail.quantity
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.quantity
     *
     * @param quantity the value for meituan_order_detail.quantity
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.price
     *
     * @return the value of meituan_order_detail.price
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.price
     *
     * @param price the value for meituan_order_detail.price
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.box_num
     *
     * @return the value of meituan_order_detail.box_num
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public Integer getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.box_num
     *
     * @param boxNum the value for meituan_order_detail.box_num
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setBoxNum(Integer boxNum) {
        this.boxNum = boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.box_price
     *
     * @return the value of meituan_order_detail.box_price
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public BigDecimal getBoxPrice() {
        return boxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.box_price
     *
     * @param boxPrice the value for meituan_order_detail.box_price
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setBoxPrice(BigDecimal boxPrice) {
        this.boxPrice = boxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.unit
     *
     * @return the value of meituan_order_detail.unit
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.unit
     *
     * @param unit the value for meituan_order_detail.unit
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meituan_order_detail.food_discount
     *
     * @return the value of meituan_order_detail.food_discount
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public BigDecimal getFoodDiscount() {
        return foodDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meituan_order_detail.food_discount
     *
     * @param foodDiscount the value for meituan_order_detail.food_discount
     *
     * @mbggenerated Tue Sep 08 17:11:12 CST 2015
     */
    public void setFoodDiscount(BigDecimal foodDiscount) {
        this.foodDiscount = foodDiscount;
    }
}