package com.meituan.chargerecord.mapper;

import com.meituan.chargerecord.entity.ChargeRecord;
import com.meituan.chargerecord.entity.ChargeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChargeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int countByExample(ChargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int deleteByExample(ChargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int deleteByPrimaryKey(Integer record_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int insert(ChargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int insertSelective(ChargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	List<ChargeRecord> selectByExample(ChargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	ChargeRecord selectByPrimaryKey(Integer record_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ChargeRecord record, @Param("example") ChargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int updateByExample(@Param("record") ChargeRecord record, @Param("example") ChargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int updateByPrimaryKeySelective(ChargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_record
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	int updateByPrimaryKey(ChargeRecord record);
}