package com.meituan.chargerecord.entity;

import java.util.Date;

public class ChargeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.record_id
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private Integer record_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.app_id
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private String app_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.app_poi_code
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private String app_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czsj
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private Date czsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czns
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private Integer czns;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czje
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private Float czje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czfs
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	private String czfs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.record_id
	 * @return  the value of charge_record.record_id
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public Integer getRecord_id() {
		return record_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.record_id
	 * @param record_id  the value for charge_record.record_id
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setRecord_id(Integer record_id) {
		this.record_id = record_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.app_id
	 * @return  the value of charge_record.app_id
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public String getApp_id() {
		return app_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.app_id
	 * @param app_id  the value for charge_record.app_id
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setApp_id(String app_id) {
		this.app_id = app_id == null ? null : app_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.app_poi_code
	 * @return  the value of charge_record.app_poi_code
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public String getApp_poi_code() {
		return app_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.app_poi_code
	 * @param app_poi_code  the value for charge_record.app_poi_code
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setApp_poi_code(String app_poi_code) {
		this.app_poi_code = app_poi_code == null ? null : app_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czsj
	 * @return  the value of charge_record.czsj
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public Date getCzsj() {
		return czsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czsj
	 * @param czsj  the value for charge_record.czsj
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setCzsj(Date czsj) {
		this.czsj = czsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czns
	 * @return  the value of charge_record.czns
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public Integer getCzns() {
		return czns;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czns
	 * @param czns  the value for charge_record.czns
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setCzns(Integer czns) {
		this.czns = czns;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czje
	 * @return  the value of charge_record.czje
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public Float getCzje() {
		return czje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czje
	 * @param czje  the value for charge_record.czje
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setCzje(Float czje) {
		this.czje = czje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czfs
	 * @return  the value of charge_record.czfs
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public String getCzfs() {
		return czfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czfs
	 * @param czfs  the value for charge_record.czfs
	 * @mbggenerated  Wed Dec 16 21:44:58 CST 2015
	 */
	public void setCzfs(String czfs) {
		this.czfs = czfs == null ? null : czfs.trim();
	}
}