package com.meituan.chargerecord.entity;

import java.util.Date;

public class ChargeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.record_id
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private Integer record_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.poi_id
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private Integer poi_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.poi_name
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private String poi_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czsj
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private Date czsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czns
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private Integer czns;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czje
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private Float czje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czfs
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private String czfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.jyh
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private String jyh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.out_trade_no
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	private String out_trade_no;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.record_id
	 * @return  the value of charge_record.record_id
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public Integer getRecord_id() {
		return record_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.record_id
	 * @param record_id  the value for charge_record.record_id
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setRecord_id(Integer record_id) {
		this.record_id = record_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.poi_id
	 * @return  the value of charge_record.poi_id
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public Integer getPoi_id() {
		return poi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.poi_id
	 * @param poi_id  the value for charge_record.poi_id
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setPoi_id(Integer poi_id) {
		this.poi_id = poi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.poi_name
	 * @return  the value of charge_record.poi_name
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public String getPoi_name() {
		return poi_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.poi_name
	 * @param poi_name  the value for charge_record.poi_name
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setPoi_name(String poi_name) {
		this.poi_name = poi_name == null ? null : poi_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czsj
	 * @return  the value of charge_record.czsj
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public Date getCzsj() {
		return czsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czsj
	 * @param czsj  the value for charge_record.czsj
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setCzsj(Date czsj) {
		this.czsj = czsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czns
	 * @return  the value of charge_record.czns
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public Integer getCzns() {
		return czns;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czns
	 * @param czns  the value for charge_record.czns
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setCzns(Integer czns) {
		this.czns = czns;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czje
	 * @return  the value of charge_record.czje
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public Float getCzje() {
		return czje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czje
	 * @param czje  the value for charge_record.czje
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setCzje(Float czje) {
		this.czje = czje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czfs
	 * @return  the value of charge_record.czfs
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public String getCzfs() {
		return czfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czfs
	 * @param czfs  the value for charge_record.czfs
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setCzfs(String czfs) {
		this.czfs = czfs == null ? null : czfs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.jyh
	 * @return  the value of charge_record.jyh
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public String getJyh() {
		return jyh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.jyh
	 * @param jyh  the value for charge_record.jyh
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setJyh(String jyh) {
		this.jyh = jyh == null ? null : jyh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.out_trade_no
	 * @return  the value of charge_record.out_trade_no
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public String getOut_trade_no() {
		return out_trade_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.out_trade_no
	 * @param out_trade_no  the value for charge_record.out_trade_no
	 * @mbggenerated  Tue Jan 05 21:37:52 CST 2016
	 */
	public void setOut_trade_no(String out_trade_no) {
		this.out_trade_no = out_trade_no == null ? null : out_trade_no.trim();
	}
}