package com.meituan.chargerecord.entity;

import java.util.Date;

public class ChargeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.record_id
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private Integer record_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.poi_id
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private Integer poi_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.poi_name
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private String poi_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czsj
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private Date czsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czns
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private Integer czns;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czje
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private Float czje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column charge_record.czfs
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	private String czfs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.record_id
	 * @return  the value of charge_record.record_id
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public Integer getRecord_id() {
		return record_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.record_id
	 * @param record_id  the value for charge_record.record_id
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setRecord_id(Integer record_id) {
		this.record_id = record_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.poi_id
	 * @return  the value of charge_record.poi_id
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public Integer getPoi_id() {
		return poi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.poi_id
	 * @param poi_id  the value for charge_record.poi_id
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setPoi_id(Integer poi_id) {
		this.poi_id = poi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.poi_name
	 * @return  the value of charge_record.poi_name
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public String getPoi_name() {
		return poi_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.poi_name
	 * @param poi_name  the value for charge_record.poi_name
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setPoi_name(String poi_name) {
		this.poi_name = poi_name == null ? null : poi_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czsj
	 * @return  the value of charge_record.czsj
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public Date getCzsj() {
		return czsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czsj
	 * @param czsj  the value for charge_record.czsj
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setCzsj(Date czsj) {
		this.czsj = czsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czns
	 * @return  the value of charge_record.czns
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public Integer getCzns() {
		return czns;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czns
	 * @param czns  the value for charge_record.czns
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setCzns(Integer czns) {
		this.czns = czns;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czje
	 * @return  the value of charge_record.czje
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public Float getCzje() {
		return czje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czje
	 * @param czje  the value for charge_record.czje
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setCzje(Float czje) {
		this.czje = czje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column charge_record.czfs
	 * @return  the value of charge_record.czfs
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public String getCzfs() {
		return czfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column charge_record.czfs
	 * @param czfs  the value for charge_record.czfs
	 * @mbggenerated  Sun Dec 27 22:43:24 CST 2015
	 */
	public void setCzfs(String czfs) {
		this.czfs = czfs == null ? null : czfs.trim();
	}
}