package com.meituan.users.entity;

public class LoginUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_users.user_id
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_users.login_id
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    private String login_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_users.login_pass
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    private String login_pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_users.nfdj
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    private Float nfdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_users.descption
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    private String descption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_users.user_id
     *
     * @return the value of login_users.user_id
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_users.user_id
     *
     * @param user_id the value for login_users.user_id
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_users.login_id
     *
     * @return the value of login_users.login_id
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public String getLogin_id() {
        return login_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_users.login_id
     *
     * @param login_id the value for login_users.login_id
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public void setLogin_id(String login_id) {
        this.login_id = login_id == null ? null : login_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_users.login_pass
     *
     * @return the value of login_users.login_pass
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public String getLogin_pass() {
        return login_pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_users.login_pass
     *
     * @param login_pass the value for login_users.login_pass
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public void setLogin_pass(String login_pass) {
        this.login_pass = login_pass == null ? null : login_pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_users.nfdj
     *
     * @return the value of login_users.nfdj
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public Float getNfdj() {
        return nfdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_users.nfdj
     *
     * @param nfdj the value for login_users.nfdj
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public void setNfdj(Float nfdj) {
        this.nfdj = nfdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_users.descption
     *
     * @return the value of login_users.descption
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public String getDescption() {
        return descption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_users.descption
     *
     * @param descption the value for login_users.descption
     *
     * @mbggenerated Sun Dec 20 13:55:13 CST 2015
     */
    public void setDescption(String descption) {
        this.descption = descption == null ? null : descption.trim();
    }
}