package com.meituan.apppoi.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppPoiExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public AppPoiExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andApp_poi_codeIsNull() {
			addCriterion("app_poi_code is null");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeIsNotNull() {
			addCriterion("app_poi_code is not null");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeEqualTo(String value) {
			addCriterion("app_poi_code =", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotEqualTo(String value) {
			addCriterion("app_poi_code <>", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeGreaterThan(String value) {
			addCriterion("app_poi_code >", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeGreaterThanOrEqualTo(String value) {
			addCriterion("app_poi_code >=", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeLessThan(String value) {
			addCriterion("app_poi_code <", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeLessThanOrEqualTo(String value) {
			addCriterion("app_poi_code <=", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeLike(String value) {
			addCriterion("app_poi_code like", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotLike(String value) {
			addCriterion("app_poi_code not like", value, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeIn(List<String> values) {
			addCriterion("app_poi_code in", values, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotIn(List<String> values) {
			addCriterion("app_poi_code not in", values, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeBetween(String value1, String value2) {
			addCriterion("app_poi_code between", value1, value2, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andApp_poi_codeNotBetween(String value1, String value2) {
			addCriterion("app_poi_code not between", value1, value2, "app_poi_code");
			return (Criteria) this;
		}

		public Criteria andAppidIsNull() {
			addCriterion("appid is null");
			return (Criteria) this;
		}

		public Criteria andAppidIsNotNull() {
			addCriterion("appid is not null");
			return (Criteria) this;
		}

		public Criteria andAppidEqualTo(String value) {
			addCriterion("appid =", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotEqualTo(String value) {
			addCriterion("appid <>", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThan(String value) {
			addCriterion("appid >", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThanOrEqualTo(String value) {
			addCriterion("appid >=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThan(String value) {
			addCriterion("appid <", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThanOrEqualTo(String value) {
			addCriterion("appid <=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLike(String value) {
			addCriterion("appid like", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotLike(String value) {
			addCriterion("appid not like", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidIn(List<String> values) {
			addCriterion("appid in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotIn(List<String> values) {
			addCriterion("appid not in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidBetween(String value1, String value2) {
			addCriterion("appid between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotBetween(String value1, String value2) {
			addCriterion("appid not between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameIsNull() {
			addCriterion("wm_poi_name is null");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameIsNotNull() {
			addCriterion("wm_poi_name is not null");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameEqualTo(String value) {
			addCriterion("wm_poi_name =", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameNotEqualTo(String value) {
			addCriterion("wm_poi_name <>", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameGreaterThan(String value) {
			addCriterion("wm_poi_name >", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameGreaterThanOrEqualTo(String value) {
			addCriterion("wm_poi_name >=", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameLessThan(String value) {
			addCriterion("wm_poi_name <", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameLessThanOrEqualTo(String value) {
			addCriterion("wm_poi_name <=", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameLike(String value) {
			addCriterion("wm_poi_name like", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameNotLike(String value) {
			addCriterion("wm_poi_name not like", value, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameIn(List<String> values) {
			addCriterion("wm_poi_name in", values, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameNotIn(List<String> values) {
			addCriterion("wm_poi_name not in", values, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameBetween(String value1, String value2) {
			addCriterion("wm_poi_name between", value1, value2, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_nameNotBetween(String value1, String value2) {
			addCriterion("wm_poi_name not between", value1, value2, "wm_poi_name");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressIsNull() {
			addCriterion("wm_poi_address is null");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressIsNotNull() {
			addCriterion("wm_poi_address is not null");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressEqualTo(String value) {
			addCriterion("wm_poi_address =", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressNotEqualTo(String value) {
			addCriterion("wm_poi_address <>", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressGreaterThan(String value) {
			addCriterion("wm_poi_address >", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressGreaterThanOrEqualTo(String value) {
			addCriterion("wm_poi_address >=", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressLessThan(String value) {
			addCriterion("wm_poi_address <", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressLessThanOrEqualTo(String value) {
			addCriterion("wm_poi_address <=", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressLike(String value) {
			addCriterion("wm_poi_address like", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressNotLike(String value) {
			addCriterion("wm_poi_address not like", value, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressIn(List<String> values) {
			addCriterion("wm_poi_address in", values, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressNotIn(List<String> values) {
			addCriterion("wm_poi_address not in", values, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressBetween(String value1, String value2) {
			addCriterion("wm_poi_address between", value1, value2, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_addressNotBetween(String value1, String value2) {
			addCriterion("wm_poi_address not between", value1, value2, "wm_poi_address");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneIsNull() {
			addCriterion("wm_poi_phone is null");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneIsNotNull() {
			addCriterion("wm_poi_phone is not null");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneEqualTo(String value) {
			addCriterion("wm_poi_phone =", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneNotEqualTo(String value) {
			addCriterion("wm_poi_phone <>", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneGreaterThan(String value) {
			addCriterion("wm_poi_phone >", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneGreaterThanOrEqualTo(String value) {
			addCriterion("wm_poi_phone >=", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneLessThan(String value) {
			addCriterion("wm_poi_phone <", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneLessThanOrEqualTo(String value) {
			addCriterion("wm_poi_phone <=", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneLike(String value) {
			addCriterion("wm_poi_phone like", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneNotLike(String value) {
			addCriterion("wm_poi_phone not like", value, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneIn(List<String> values) {
			addCriterion("wm_poi_phone in", values, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneNotIn(List<String> values) {
			addCriterion("wm_poi_phone not in", values, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneBetween(String value1, String value2) {
			addCriterion("wm_poi_phone between", value1, value2, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andWm_poi_phoneNotBetween(String value1, String value2) {
			addCriterion("wm_poi_phone not between", value1, value2, "wm_poi_phone");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Float value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Float value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Float value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Float value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Float value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Float value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Float> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Float> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Float value1, Float value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Float value1, Float value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Float value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Float value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Float value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Float value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Float value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Float value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Float> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Float> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Float value1, Float value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Float value1, Float value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andDescptionIsNull() {
			addCriterion("descption is null");
			return (Criteria) this;
		}

		public Criteria andDescptionIsNotNull() {
			addCriterion("descption is not null");
			return (Criteria) this;
		}

		public Criteria andDescptionEqualTo(String value) {
			addCriterion("descption =", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionNotEqualTo(String value) {
			addCriterion("descption <>", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionGreaterThan(String value) {
			addCriterion("descption >", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionGreaterThanOrEqualTo(String value) {
			addCriterion("descption >=", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionLessThan(String value) {
			addCriterion("descption <", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionLessThanOrEqualTo(String value) {
			addCriterion("descption <=", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionLike(String value) {
			addCriterion("descption like", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionNotLike(String value) {
			addCriterion("descption not like", value, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionIn(List<String> values) {
			addCriterion("descption in", values, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionNotIn(List<String> values) {
			addCriterion("descption not in", values, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionBetween(String value1, String value2) {
			addCriterion("descption between", value1, value2, "descption");
			return (Criteria) this;
		}

		public Criteria andDescptionNotBetween(String value1, String value2) {
			addCriterion("descption not between", value1, value2, "descption");
			return (Criteria) this;
		}

		public Criteria andExpiredateIsNull() {
			addCriterion("expiredate is null");
			return (Criteria) this;
		}

		public Criteria andExpiredateIsNotNull() {
			addCriterion("expiredate is not null");
			return (Criteria) this;
		}

		public Criteria andExpiredateEqualTo(Date value) {
			addCriterion("expiredate =", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateNotEqualTo(Date value) {
			addCriterion("expiredate <>", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateGreaterThan(Date value) {
			addCriterion("expiredate >", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateGreaterThanOrEqualTo(Date value) {
			addCriterion("expiredate >=", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateLessThan(Date value) {
			addCriterion("expiredate <", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateLessThanOrEqualTo(Date value) {
			addCriterion("expiredate <=", value, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateIn(List<Date> values) {
			addCriterion("expiredate in", values, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateNotIn(List<Date> values) {
			addCriterion("expiredate not in", values, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateBetween(Date value1, Date value2) {
			addCriterion("expiredate between", value1, value2, "expiredate");
			return (Criteria) this;
		}

		public Criteria andExpiredateNotBetween(Date value1, Date value2) {
			addCriterion("expiredate not between", value1, value2, "expiredate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_poi
	 * @mbggenerated  Wed Dec 23 22:56:44 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_poi
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 02 19:50:59 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}