package com.meituan.apppoi.entity;

import java.util.Date;

public class AppPoi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.poi_id
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private Integer poi_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.app_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String app_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.bd_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String bd_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.bd_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String bd_appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.eleme_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String eleme_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.eleme_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String eleme_appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.kb_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String kb_poi_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.kb_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String kb_appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.userid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.wm_poi_name
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String wm_poi_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.wm_poi_address
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String wm_poi_address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.wm_poi_phone
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String wm_poi_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.amount
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private Float amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.price
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.descption
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private String descption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_poi.expiredate
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	private Date expiredate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.poi_id
	 * @return  the value of app_poi.poi_id
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public Integer getPoi_id() {
		return poi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.poi_id
	 * @param poi_id  the value for app_poi.poi_id
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setPoi_id(Integer poi_id) {
		this.poi_id = poi_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.app_poi_code
	 * @return  the value of app_poi.app_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getApp_poi_code() {
		return app_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.app_poi_code
	 * @param app_poi_code  the value for app_poi.app_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setApp_poi_code(String app_poi_code) {
		this.app_poi_code = app_poi_code == null ? null : app_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.appid
	 * @return  the value of app_poi.appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.appid
	 * @param appid  the value for app_poi.appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.bd_poi_code
	 * @return  the value of app_poi.bd_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getBd_poi_code() {
		return bd_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.bd_poi_code
	 * @param bd_poi_code  the value for app_poi.bd_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setBd_poi_code(String bd_poi_code) {
		this.bd_poi_code = bd_poi_code == null ? null : bd_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.bd_appid
	 * @return  the value of app_poi.bd_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getBd_appid() {
		return bd_appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.bd_appid
	 * @param bd_appid  the value for app_poi.bd_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setBd_appid(String bd_appid) {
		this.bd_appid = bd_appid == null ? null : bd_appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.eleme_poi_code
	 * @return  the value of app_poi.eleme_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getEleme_poi_code() {
		return eleme_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.eleme_poi_code
	 * @param eleme_poi_code  the value for app_poi.eleme_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setEleme_poi_code(String eleme_poi_code) {
		this.eleme_poi_code = eleme_poi_code == null ? null : eleme_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.eleme_appid
	 * @return  the value of app_poi.eleme_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getEleme_appid() {
		return eleme_appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.eleme_appid
	 * @param eleme_appid  the value for app_poi.eleme_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setEleme_appid(String eleme_appid) {
		this.eleme_appid = eleme_appid == null ? null : eleme_appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.kb_poi_code
	 * @return  the value of app_poi.kb_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getKb_poi_code() {
		return kb_poi_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.kb_poi_code
	 * @param kb_poi_code  the value for app_poi.kb_poi_code
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setKb_poi_code(String kb_poi_code) {
		this.kb_poi_code = kb_poi_code == null ? null : kb_poi_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.kb_appid
	 * @return  the value of app_poi.kb_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getKb_appid() {
		return kb_appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.kb_appid
	 * @param kb_appid  the value for app_poi.kb_appid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setKb_appid(String kb_appid) {
		this.kb_appid = kb_appid == null ? null : kb_appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.userid
	 * @return  the value of app_poi.userid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.userid
	 * @param userid  the value for app_poi.userid
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.wm_poi_name
	 * @return  the value of app_poi.wm_poi_name
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getWm_poi_name() {
		return wm_poi_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.wm_poi_name
	 * @param wm_poi_name  the value for app_poi.wm_poi_name
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setWm_poi_name(String wm_poi_name) {
		this.wm_poi_name = wm_poi_name == null ? null : wm_poi_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.wm_poi_address
	 * @return  the value of app_poi.wm_poi_address
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getWm_poi_address() {
		return wm_poi_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.wm_poi_address
	 * @param wm_poi_address  the value for app_poi.wm_poi_address
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setWm_poi_address(String wm_poi_address) {
		this.wm_poi_address = wm_poi_address == null ? null : wm_poi_address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.wm_poi_phone
	 * @return  the value of app_poi.wm_poi_phone
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getWm_poi_phone() {
		return wm_poi_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.wm_poi_phone
	 * @param wm_poi_phone  the value for app_poi.wm_poi_phone
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setWm_poi_phone(String wm_poi_phone) {
		this.wm_poi_phone = wm_poi_phone == null ? null : wm_poi_phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.amount
	 * @return  the value of app_poi.amount
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public Float getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.amount
	 * @param amount  the value for app_poi.amount
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setAmount(Float amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.price
	 * @return  the value of app_poi.price
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.price
	 * @param price  the value for app_poi.price
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.descption
	 * @return  the value of app_poi.descption
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public String getDescption() {
		return descption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.descption
	 * @param descption  the value for app_poi.descption
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setDescption(String descption) {
		this.descption = descption == null ? null : descption.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_poi.expiredate
	 * @return  the value of app_poi.expiredate
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public Date getExpiredate() {
		return expiredate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_poi.expiredate
	 * @param expiredate  the value for app_poi.expiredate
	 * @mbggenerated  Sun Dec 27 21:48:44 CST 2015
	 */
	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}
}